title: TinyTools
description: Tiny scripts to improve your productivity.
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal
show_downloads: false
logo: ./tinytools.jpg

main_url: https://github.com/TinyToolSH/ 

permalink: /projects/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: projects/page:num
