title: TinyTools
description: Tiny scripts to improve your productivity.
#theme: jekyll-theme-slate
theme: jekyll-theme-minimal
show_downloads: false
#logo: ./tinytools.jpg

main_url: https://github.com/TinyToolSH/ 

projects:
    tgoeswall:
        version: 0.0.1
    tmenu:
        version: 0.0.1
    tnotes:
        version: 0.0.1
    tpomodoro:
        version: 0.0.1
    tprogbar:
        version: 0.0.1
    tsearch:
        version: 0.0.1
    ttodo:
        version: 0.0.1
    tyaml:
        version: 0.0.1

github:
  zip_url: https://github.com/Calebe94/tinytools/archive/refs/tags/0.9.0.zip
  tar_url: https://github.com/Calebe94/tinytools/archive/refs/tags/0.9.0.tar.gz
  repository_url: https://github.com/Calebe94/tinytools


permalink: /projects/:title

# jekyll-paginate. for paginating blog posts.
paginate: 5
paginate_path: projects/page:num
